title: Wooben IT
baseURL: /
params:
  color_scheme: light
  accent_color: pink
  header:
    title: Wooben
    has_nav: true
    logo_img: /images/w2.png
  footer:
    content: "&copy; 2020 Wooben, LLC. All rights reserved."
    links: []
    has_social: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
